name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '9 * * * *'
    
jobs:
  scheduled:
    runs-on: ubuntu-latest
    env:
      SUPER_SECRET: ${{ secrets.BEARER_TOKEN }}
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.7
        
#     - name: Setup Node.js environment
#       uses: actions/setup-node@v2.1.5
#       with:
#         node-version: 12
        
    - name: Fetch latest data
      run: |-
       echo $BEARER_TOKEN
        ( \
          cd etl                          && \
          pip install -r requirements.txt && \
          python main.py                     \
        )

    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
